# Generated by Django 3.2.1 on 2021-05-12 21:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='city',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='state',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='street',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.URLField(default='null', help_text='Add the pdf file from DNR describing the project.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='zip_code',
            field=models.CharField(default='null', max_length=11),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Property',
        ),
    ]
