# Generated by Django 3.2.1 on 2021-05-13 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_project_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='expiration_date',
            field=models.DateField(help_text='Date cost share agreement expires', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='reimbursement',
            field=models.DecimalField(decimal_places=2, default=6.0, max_digits=6),
            preserve_default=False,
        ),
    ]
