# Generated by Django 3.2.1 on 2021-06-07 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_project_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.URLField(blank=True, help_text='Add the pdf file from DNR describing the project.', null=True),
        ),
    ]
